import { test, expect } from '@playwright/test';
test.use({ viewport: { width: 390, height: 844 } });
test('six service categories have independent complete pages and separate company tab', async ({ page }) => {
  await page.goto('/#/directory');
  await expect(page.locator('.directory-category')).toHaveCount(6);
  await expect(page.getByText('企业名录待上架', { exact: true })).toHaveCount(0);
  await page.screenshot({ path: '../analysis/u12-directory.png', fullPage: true });
  await page.locator('.directory-category').nth(1).click();
  await expect(page).toHaveURL(/#\/directory\/2$/);
  await expect(page.locator('.directory-module')).toHaveCount(5);
  await expect(page.locator('.directory-module').first()).toContainText('材料准备');
  await expect(page.locator('.directory-module').first()).toContainText('痛点');
  await page.screenshot({ path: '../analysis/u12-service-detail.png', fullPage: true });
  await page.reload(); await expect(page.locator('.directory-module')).toHaveCount(5);
  await page.goto('/#/directory');
  await page.getByRole('tab', { name: '会员企业', exact: true }).click();
  await expect(page.getByRole('heading', { name: '会员企业资料整理中' })).toBeVisible();
  await expect(page.locator('.directory-category')).toHaveCount(0);
});
test('campaign is dismissible, does not repeat, reopens from activities and expires without home space', async ({ page }) => {
  const campaign = { id: 'ui-isolated-campaign', active: true, title: '测试活动', timeLabel: '9月17日 14:30—16:30', venue: '南宁国际会展中心 B103、B105', endsAt: new Date(Date.now() + 600000).toISOString() };
  await page.route('**/api/campaign', r => r.fulfill({ json: { campaign } }));
  await page.goto('/#/');
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.screenshot({ path: '../analysis/u12-campaign.png', fullPage: true });
  await page.getByRole('button', { name: '关闭活动邀请' }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  const before = await page.locator('.club-brand-hero').boundingBox();
  await page.reload(); await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.goto('/#/activities');
  await page.locator('.campaign-entry').click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).not.toBeVisible();
  campaign.active = false;
  await page.goto('/#/');
  await expect(page.locator('.club-brand-hero')).toBeVisible();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const after = await page.locator('.club-brand-hero').boundingBox();
  expect(after?.y).toBe(before?.y);
  await page.goto('/#/activities'); await expect(page.locator('.campaign-entry')).toHaveCount(0);
});
