import {test,expect,type Page} from '@playwright/test';
const password='OnlyInIsolatedTests1',base='/hejun-club/';
async function login(page:Page,username:string,admin=false){await page.goto(base+(admin?'#/admin':'#/account'));await page.getByRole('textbox',{name:'账号',exact:true}).fill(username);await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('heading',{name:admin?'运营工作台':'我的订单',exact:true})).toBeVisible();}
async function register(page:Page,username:string){await page.goto(base+'#/account');await page.getByRole('button',{name:'没有账号，创建内测账号'}).click();await page.getByRole('textbox',{name:'账号',exact:true}).fill(username);await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('checkbox').check();await page.getByRole('button',{name:'注册并登录'}).click();await expect(page.getByRole('heading',{name:'我的订单',exact:true})).toBeVisible();}
test('server-backed web journey: draft, reject/reapply, approve/cancel, relogin, feedback/reply/confirm and published content',async({page,browser})=>{
 const username='web_'+Date.now();await register(page,username);
 await page.goto(base+'#/join/organization');await page.getByRole('textbox',{name:'姓名 / 称呼'}).fill('隔离网页申请');await page.getByRole('textbox',{name:'手机号码'}).fill('13800000000');await page.getByRole('textbox',{name:'所在城市'}).fill('测试城市');await page.getByRole('textbox',{name:'机构名称'}).fill('隔离测试机构');await page.reload();await expect(page.getByRole('textbox',{name:'姓名 / 称呼'})).toHaveValue('隔离网页申请');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'提交资质申请',exact:true}).click();await expect(page).toHaveURL(/checkout/);const original=page.url().split('/').at(-1)!;
 const adminContext=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000}}),admin=await adminContext.newPage();
 try{await login(admin,'test_admin',true);const card=admin.locator('article').filter({hasText:original});await card.getByLabel('资质核验 / 驳回说明').fill('请补充机构名称');await card.getByRole('button',{name:'驳回申请',exact:true}).click();await expect(admin.getByRole('status')).toContainText('审核已保存');
 await page.reload();await expect(page.getByText('请补充机构名称',{exact:true})).toBeVisible();await page.getByRole('link',{name:'修改资料，重新申请'}).click();await expect(page.getByRole('textbox',{name:'姓名 / 称呼'})).toHaveValue('隔离网页申请');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'提交资质申请',exact:true}).click();await expect(page).toHaveURL(/checkout/);const current=page.url().split('/').at(-1)!;expect(current).not.toBe(original);
 await admin.reload();const card2=admin.locator('article').filter({hasText:current});await card2.getByLabel('资质核验 / 驳回说明').fill('隔离资料已核对');await card2.getByRole('button',{name:'资质通过，允许付款'}).click();await expect(admin.getByRole('status')).toContainText('审核已保存');await page.reload();await expect(page.getByRole('heading',{name:'待付款',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'退出登录',exact:true}).click();await login(page,username);await expect(page.getByRole('tabpanel')).toContainText(current);await page.getByRole('link').filter({hasText:current}).click();await page.getByRole('button',{name:'取消订单',exact:true}).click();await page.getByRole('button',{name:'确认取消订单'}).click();await expect(page.getByRole('heading',{name:'已取消',exact:true})).toBeVisible();
 await page.goto(base+'#/feedback/new');await page.getByLabel('问题标题',{exact:true}).fill('网页体验问题');await page.getByLabel('问题描述',{exact:true}).fill('需要核实服务资料');await page.getByRole('button',{name:'提交问题',exact:true}).click();await expect(page).toHaveURL(/feedback\/[a-f0-9-]+/);
 await admin.getByRole('tab',{name:'帮助反馈',exact:true}).click();await admin.locator('article').filter({hasText:'网页体验问题'}).getByRole('button',{name:'查看并处理'}).click();await admin.getByLabel('回复内容',{exact:true}).fill('已收到，相关资料正在整理。');await admin.getByLabel('回复后的状态',{exact:true}).selectOption('resolved');await admin.getByRole('button',{name:/保存回复/}).click();await expect(admin.getByRole('status')).toContainText('回复已保存');
 await page.reload();await expect(page.getByText('已收到，相关资料正在整理。',{exact:true})).toBeVisible();await page.getByRole('button',{name:'确认问题已解决'}).click();await expect(page.getByText('已确认解决',{exact:true})).toBeVisible();
 await admin.getByRole('tab',{name:'资讯与知识',exact:true}).click();await admin.getByLabel('内容标题',{exact:true}).fill('隔离知识');await admin.getByLabel('内容正文',{exact:true}).fill('这是隔离测试正文');await admin.getByLabel('阅读范围',{exact:true}).selectOption('public');await admin.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(admin.getByRole('status')).toContainText('草稿已保存');await admin.getByRole('button',{name:'发布内容',exact:true}).click();await admin.getByRole('button',{name:'确认发布',exact:true}).click();await expect(admin.getByRole('status')).toContainText('已发布');await page.goto(base+'#/articles');await page.getByRole('link').filter({hasText:'隔离知识'}).click();await expect(page.getByText('这是隔离测试正文',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
 const cookies=await page.context().cookies();expect(cookies.find(c=>c.name==='club_web_session')).toMatchObject({secure:true,httpOnly:true,path:'/hejun-club/api'});
 }finally{await adminContext.close();}
});
