import {test,expect} from '@playwright/test';
test('operator creates, previews, publishes, reloads and withdraws an activity visible to visitors',async({page,browser})=>{
 await page.goto('/hejun-club/#/admin');await page.getByRole('textbox',{name:'账号',exact:true}).fill('test_admin');await page.getByLabel('密码',{exact:true}).fill('OnlyInIsolatedTests1');await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByRole('tab',{name:'活动发布',exact:true}).click();
 await page.getByLabel('活动名称',{exact:true}).fill('隔离活动发布联验');await page.getByLabel('活动简介',{exact:true}).fill('隔离活动简介');await page.getByLabel('开始时间（北京时间）').fill('2099-01-01T09:00');await page.getByLabel('结束时间（北京时间）').fill('2099-01-01T11:00');await page.getByLabel('活动地点',{exact:true}).fill('测试城市测试会场');await page.getByLabel('主办方',{exact:true}).fill('隔离主办方');await page.getByLabel('活动详情',{exact:true}).fill('议程一\n议程二');await page.getByRole('button',{name:'预览活动',exact:true}).click();await expect(page.getByRole('region',{name:'活动预览'})).toContainText('隔离主办方');
 await page.getByRole('button',{name:'保存活动草稿',exact:true}).click();await expect(page.getByRole('status')).toContainText('活动草稿已保存');await page.getByRole('button',{name:'发布活动',exact:true}).click();await page.getByRole('button',{name:'确认发布活动',exact:true}).click();await expect(page.getByRole('status')).toContainText('活动已发布');
 const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:390,height:844}}),guest=await context.newPage();
 try{await guest.goto('https://127.0.0.1:5228/hejun-club/#/activities');await guest.getByRole('link').filter({hasText:'隔离活动发布联验'}).click();await expect(guest.getByRole('heading',{name:'隔离活动发布联验',exact:true})).toBeVisible();await expect(guest.getByText('测试城市测试会场',{exact:true})).toBeVisible();expect(await guest.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
  await page.reload();await page.getByRole('tab',{name:'活动发布',exact:true}).click();await page.getByRole('button').filter({hasText:'隔离活动发布联验'}).click();await expect(page.getByLabel('活动名称',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'撤下活动',exact:true}).click();await page.getByRole('button',{name:'确认撤下活动',exact:true}).click();await expect(page.getByRole('status')).toContainText('活动已撤下');await guest.reload();await expect(guest.getByRole('alert')).toContainText('活动不存在或已撤下');
 }finally{await context.close();}
});
