import {useEffect,useRef,useState} from 'react';
import {api,errorText} from './api';
import type {Session} from './api';
import './admin-articles.css';
type Content={title:string;summary:string;body:string;mode:'online'|'offline';startAt:string;endAt:string;location:string;organizer:string};
type Activity=Content&{id:string;status:'draft'|'published';revision:number};
const blank=():Content=>({title:'',summary:'',body:'',mode:'offline',startAt:'',endAt:'',location:'',organizer:''});
const date=(value:string)=>value?new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'待填写';
const localInput=(value:string)=>value?new Date(Date.parse(value)+8*3600000).toISOString().slice(0,16):'';
const edit=(item:Content):Content=>({...blank(),...Object.fromEntries(Object.keys(blank()).map(key=>[key,item[key as keyof Content]]))});
const state=(item:Activity)=>Date.parse(item.endAt)<Date.now()?'已结束':Date.parse(item.startAt)>Date.now()?'即将开始':'进行中';
function Details({item}:{item:Content}){return <><p>{item.summary}</p><dl className="order-details"><div><dt>活动形式</dt><dd>{item.mode==='online'?'线上活动':'线下活动'}</dd></div><div><dt>活动时间（北京时间）</dt><dd>{date(item.startAt)} 至 {date(item.endAt)}</dd></div><div><dt>{item.mode==='online'?'参与说明':'活动地点'}</dt><dd>{item.location||'待填写'}</dd></div><div><dt>主办方</dt><dd>{item.organizer||'待填写'}</dd></div></dl><h3>活动详情</h3><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{item.body}</p></>;}
export function WebActivities({id}:{id:string}){
 const [items,setItems]=useState<Activity[]>([]),[item,setItem]=useState<Activity|null>(null),[error,setError]=useState(''),[ready,setReady]=useState(false),[query,setQuery]=useState('');
 useEffect(()=>{let active=true;setItem(null);setItems([]);setReady(false);setError('');api<{activities?:Activity[];activity?:Activity}>('/activities'+(id?'/'+id:'')).then(r=>{if(active){setItems(r.activities||[]);setItem(r.activity||null);setReady(true);}}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[id]);
 return <><div className="web-row"><h1>{item?.title||'俱乐部活动'}</h1>{id&&<a href="#/activities">返回活动列表</a>}</div>{error&&<p role="alert">{error}<button onClick={()=>location.reload()}>重新读取</button></p>}{!ready&&!error&&<p>正在读取活动…</p>}{item?<section><p>{state(item)}</p><Details item={item}/></section>:!id&&<><label className="field"><span>搜索活动</span><input value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="web-grid">{items.filter(a=>(a.title+a.summary+a.location).includes(query.trim())).map(a=><a className="web-card" key={a.id} href={'#/activities/'+a.id}><p>{a.mode==='online'?'线上活动':'线下活动'} · {state(a)}</p><h2>{a.title}</h2><p>{a.summary}</p><p>{date(a.startAt)}（北京时间）</p><p>{a.location}</p></a>)}</div>{ready&&!items.length&&<p>暂无已发布活动。</p>}{ready&&items.length>0&&!items.some(a=>(a.title+a.summary+a.location).includes(query.trim()))&&<p>没有匹配的活动，请更换关键词。</p>}</>}</>;
}
export function AdminActivities({userId}:{userId:string}){
 const [items,setItems]=useState<Activity[]>([]),[selected,setSelected]=useState<Activity|null>(null),[form,setForm]=useState<Content>(blank),[query,setQuery]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[confirm,setConfirm]=useState<'publish'|'unpublish'|null>(null),[preview,setPreview]=useState(false),[uncertain,setUncertain]=useState(false);
 const mounted=useRef(true),lock=useRef(false),pending=useRef({key:crypto.randomUUID() as string,payload:''});
 const dirty=JSON.stringify(form)!==JSON.stringify(selected?edit(selected):blank());
 async function checked(){const current=await api<Session>('/me');if(current.user?.id!==userId||current.user.role!=='admin'){if(mounted.current){setItems([]);setSelected(null);setForm(blank());}throw new Error('登录状态已变化，请重新登录。');}}
 async function run(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{await checked();if(mounted.current)await work();}catch(e){if(mounted.current)setError(errorText(e));}finally{if(mounted.current){lock.current=false;setBusy(false);}}}
 function accept(item:Activity){setSelected(item);setForm(edit(item));setItems(old=>[item,...old.filter(a=>a.id!==item.id)]);setConfirm(null);setUncertain(false);}
 async function load(){await run(async()=>{const r=await api<{activities:Activity[]}>('/admin/activities');await checked();if(mounted.current)setItems(r.activities);});}
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;};},[userId]);
 function choose(item:Activity|null){if(busy||uncertain||(dirty&&!window.confirm('放弃未保存的活动修改？')))return;setSelected(item);setForm(item?edit(item):blank());setError('');setMessage('');setConfirm(null);setPreview(false);pending.current={key:crypto.randomUUID(),payload:''};}
 async function save(){await run(async()=>{const payload=JSON.stringify(form);if(!selected&&pending.current.payload!==payload)pending.current={key:crypto.randomUUID(),payload};let r:{activity:Activity};try{r=await api('/admin/activities'+(selected?'/'+selected.id:''),{...form,...(selected?{revision:selected.revision}:{})},selected?undefined:pending.current.key);await checked();}catch(e){if(!selected&&mounted.current)setUncertain(true);throw e;}if(mounted.current){accept(r.activity);setMessage('活动草稿已保存。');}});}
 async function transition(){if(!selected||!confirm||dirty)return;const action=confirm;await run(async()=>{const r=await api<{activity:Activity}>('/admin/activities/'+selected.id+'/'+action,{revision:selected.revision});await checked();if(mounted.current){accept(r.activity);setMessage(action==='publish'?'活动已发布，访客可查看详情。':'活动已撤下，访客不再可见。');}});}
 return <section className="article-management" aria-label="活动管理"><div className="business-row"><div><h2>活动发布</h2><p>填写活动信息，预览后发布。已发布内容修改前需先撤下。</p></div><div className="business-actions"><button className="button secondary" disabled={busy||uncertain} onClick={()=>choose(null)}>新建活动</button><button className="button secondary" disabled={busy} onClick={()=>void load()}>刷新活动列表</button></div></div>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{uncertain&&<p role="alert">保存结果未确认，请重试原稿；服务器会核对同一次提交，避免重复。</p>}
 <div className="article-workspace"><div className="article-catalog"><label className="field"><span>查找活动</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label>{items.filter(i=>i.title.includes(query.trim())).map(i=><button className={'article-choice '+(selected?.id===i.id?'active':'')} key={i.id} disabled={busy||uncertain} onClick={()=>choose(i)}><strong>{i.title}</strong><span>{i.status==='draft'?'草稿':'已发布'}</span><small>{date(i.startAt)}</small></button>)}{!items.length&&<p>从新建活动开始。</p>}</div>
 <div className="form-panel article-editor"><h3>{selected?'编辑活动':'新建活动'}</h3><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy||selected?.status==='published'||uncertain}>
 <label className="field"><span>活动名称</span><input required maxLength={80} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label>
 <label className="field"><span>活动形式</span><select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value as Content['mode']})}><option value="offline">线下活动</option><option value="online">线上活动</option></select></label>
 <label className="field"><span>活动简介</span><textarea rows={2} maxLength={180} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label>
 {(['startAt','endAt'] as const).map(key=><label className="field" key={key}><span>{key==='startAt'?'开始时间':'结束时间'}（北京时间）</span><input type="datetime-local" value={localInput(form[key])} onChange={e=>setForm({...form,[key]:e.target.value?new Date(e.target.value+':00+08:00').toISOString():''})}/></label>)}
 <label className="field"><span>{form.mode==='online'?'线上参与说明':'活动地点'}</span><textarea rows={2} maxLength={300} value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label>
 <label className="field"><span>主办方</span><input maxLength={100} value={form.organizer} onChange={e=>setForm({...form,organizer:e.target.value})}/></label>
 <label className="field"><span>活动详情</span><textarea rows={9} maxLength={4000} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label></fieldset>
 {selected?.status!=='published'&&<button className="button primary" disabled={busy}>{uncertain?'重试保存活动':'保存活动草稿'}</button>}</form><div className="business-actions"><button className="button secondary" onClick={()=>setPreview(!preview)}>{preview?'收起预览':'预览活动'}</button>{selected&&<button className="button secondary" disabled={busy||dirty||uncertain} onClick={()=>setConfirm(selected.status==='published'?'unpublish':'publish')}>{selected.status==='published'?'撤下活动':'发布活动'}</button>}</div>
 {preview&&<section aria-label="活动预览"><h2>{form.title||'未填写名称'}</h2><Details item={form}/></section>}{confirm&&<div className="article-confirm"><p>{confirm==='publish'?'发布后所有访客可查看活动信息。确认发布？':'撤下后活动链接将无法查看。确认撤下？'}</p><button className="button primary" disabled={busy} onClick={()=>void transition()}>{confirm==='publish'?'确认发布活动':'确认撤下活动'}</button><button className="button secondary" onClick={()=>setConfirm(null)}>返回检查</button></div>}</div></div></section>;
}
