import {useEffect,useRef,useState} from 'react';
import {api,errorText} from './api';
import type {Session} from './api';
import {Login} from './MemberPages';
type Kind='articles'|'resources'|'feedback';
type Item={fullAccess?:boolean;document?:{filename:string;pages:number;bytes:number;previewPages?:number}|null;id:string;title:string;summary?:string;body?:string;category:string;revision?:number;status?:string;confirmedAt?:string|null;unread?:boolean;events?:{id:number;body:string;authorKind:string;createdAt:string}[];action?:{type:string;phoneNumber?:string;appId?:string;path?:string}};
const labels={articles:'知识与资讯',resources:'会员服务',feedback:'帮助与反馈'};
const status:Record<string,string>={open:'待受理',processing:'处理中',resolved:'已回复，待确认'};
export function WebContent({kind,id,session,refreshSession}:{kind:Kind;id:string;session:Session;refreshSession:()=>Promise<void>}){
 const [items,setItems]=useState<Item[]>([]),[selected,setSelected]=useState<Item|null>(null),[query,setQuery]=useState(''),[category,setCategory]=useState('all');
 const [busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[cursor,setCursor]=useState<string|null>(null);
 const draftKey='club-web-draft:'+location.pathname+':'+session.user?.id+':'+kind+':'+id;
 const pending=useRef({key:crypto.randomUUID() as string,payload:''});
 const [form,setForm]=useState(()=>{try{const d=JSON.parse(sessionStorage.getItem(draftKey)||'null');if(d&&d.at>Date.now()-86400000&&d.form&&typeof d.form.body==='string'){pending.current=d.pending;return d.form as {title:string;body:string;category:string};}}catch{}return {title:'',body:'',category:'other'};});
 const active=useRef(true),lock=useRef(false);
 useEffect(()=>{if(kind==='feedback'&&session.user&&form.body){try{sessionStorage.setItem(draftKey,JSON.stringify({at:Date.now(),form,pending:pending.current}));}catch{setError('本机草稿保存失败，请保持此页。');}}},[form,draftKey]);
 async function identity(){const current=await api<Session>('/me');if((current.user?.id||null)!==(session.user?.id||null))throw new Error('登录账号已变化，请刷新登录状态。');}
 async function run(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await identity();if(active.current)await work();}catch(e){if(active.current){setError(errorText(e));setSelected(null);setItems([]);setReady(false);}}finally{if(active.current){lock.current=false;setBusy(false);}}}
 async function load(more=false){await run(async()=>{if(id&&id!=='new'){const r=await api<{article?:Item;resource?:Item;ticket?:Item}>('/'+kind+'/'+id);await identity();if(!active.current)return;const item=(r.article||r.resource||r.ticket)!;setSelected(item);setReady(true);if(kind==='feedback'&&item.events?.length)await api('/feedback/'+id+'/read',{eventId:item.events.at(-1)!.id});}else if(id!=='new'){const r=await api<{articles?:Item[];resources?:Item[];tickets?:Item[];nextCursor?:string;hasMore?:boolean}>('/'+kind+(more&&cursor?'/before/'+cursor:''));await identity();if(!active.current)return;setItems(old=>more?[...old,...(r.tickets||[])]:r.articles||r.resources||r.tickets||[]);setCursor(r.nextCursor||null);setReady(true);}else setReady(true);});}
 useEffect(()=>{void load();return()=>{active.current=false;};},[]);
 async function send(action?:'followup'|'confirm'){
  await run(async()=>{const data=action?{revision:selected!.revision,...(action==='followup'?{body:form.body}:{})}:form;
   const payload=JSON.stringify({id,action,data});if(payload!==pending.current.payload)pending.current={key:crypto.randomUUID(),payload};
   try{sessionStorage.setItem(draftKey,JSON.stringify({at:Date.now(),form,pending:pending.current}));}catch{ /* Server persistence remains available. */ }
   const result=await api<{ticket:Item}>('/feedback'+(action?'/'+id+'/'+action:''),data,pending.current.key);
   await identity();if(!active.current)return;sessionStorage.removeItem(draftKey);setForm({title:'',body:'',category:'other'});pending.current={key:crypto.randomUUID(),payload:''};setSelected(result.ticket);
   if(!action)location.hash='/feedback/'+result.ticket.id;
  });
 }
 if(kind==='feedback'&&!session.user)return <Login refresh={refreshSession}/>;
 if(kind==='feedback'&&session.user?.role==='admin')return <section><h1>帮助与反馈</h1><p>请在运营后台受理和回复会员问题。</p><a href="#/admin">前往运营后台</a></section>;
 const visible=items.filter(i=>(category==='all'||i.category===category)&&(i.title+' '+(i.summary||'')).includes(query.trim()));
 return <><div className="web-row"><h1>{id==='new'?'提交问题':selected?.title||labels[kind]}</h1><div className="web-actions">{id?<a href={'#/'+kind}>返回列表</a>:kind==='feedback'&&<a className="button primary" href="#/feedback/new">提交问题</a>}<button className="button secondary" disabled={busy} onClick={()=>void load()}>刷新</button></div></div>
 {error&&<p role="alert">{error}<button onClick={()=>void refreshSession()}>刷新登录状态</button></p>}{busy&&<p role="status">正在处理…</p>}
 {id==='new'&&kind==='feedback'?<section><form onSubmit={e=>{e.preventDefault();void send();}}><label className="field"><span>问题标题</span><input required maxLength={60} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="field"><span>问题分类</span><select aria-label="问题分类" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="account">账号</option><option value="order">申请与订单</option><option value="content">内容</option><option value="other">其他</option></select></label><label className="field"><span>问题描述</span><textarea required maxLength={2000} rows={6} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><button className="button primary" disabled={busy}>提交问题</button></form></section>:selected?<section>
 {kind==='articles'&&selected.document&&<><p>共 {selected.document.pages} 页 · {selected.fullAccess?'全文阅读':'可试看前 '+selected.document.previewPages+' 页'}</p><div className="web-actions"><a className="button primary" target="_blank" rel="noopener noreferrer" href={'/hejun-club/api/articles/'+selected.id+(selected.fullAccess?'/document':'/preview')}>{selected.fullAccess?'阅读 PDF 全文':'阅读试看版'}</a>{selected.fullAccess?<a href={'/hejun-club/api/articles/'+selected.id+'/document?download=1'}>下载原件</a>:<a className="button secondary" href={session.user?'#/members':'#/account'}>{session.user?'了解会员，阅读全文':'会员登录阅读全文'}</a>}</div>{!selected.fullAccess&&<p>有效的基础会员、星级会员及机构会员可阅读和下载全文。</p>}</>}<p>{selected.summary}</p><p className="web-body">{selected.body}</p>
 {kind==='resources'&&<>{selected.action?.type==='phone'?<a className="button primary" href={'tel:'+selected.action.phoneNumber}>拨打服务电话 {selected.action.phoneNumber}</a>:<p>此资源通过微信小程序提供，请在原生会员端打开。网页可查看服务说明，无法直接调用微信小程序接口。</p>}</>}
 {kind==='feedback'&&<><p>{selected.confirmedAt?'已确认解决':status[selected.status||'']}</p>{selected.events?.map(event=><section key={event.id}><strong>{event.authorKind==='staff'?'运营回复':'我的补充 / 确认'}</strong><small> · {new Date(event.createdAt).toLocaleString('zh-CN')}</small><p className="web-body">{event.body}</p></section>)}{!selected.confirmedAt&&<><form onSubmit={e=>{e.preventDefault();void send('followup');}}><label className="field"><span>补充说明</span><textarea required rows={4} maxLength={2000} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><button className="button secondary" disabled={busy}>发送补充</button></form>{selected.status==='resolved'&&<button className="button primary" disabled={busy} onClick={()=>void send('confirm')}>确认问题已解决</button>}</>}</>}
 </section>:!id&&<><label className="field"><span>搜索{labels[kind]}</span><input value={query} onChange={e=>setQuery(e.target.value)}/></label>{kind==='articles'&&<label className="field"><span>内容分类</span><select aria-label="内容分类" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">全部</option><option value="knowledge">知识</option><option value="news">资讯</option></select></label>}<div className="web-grid">{visible.map(item=><a className="web-card" href={'#/'+kind+'/'+item.id} key={item.id}><h2>{item.title}</h2><p>{item.summary||status[item.status||'']}</p>{item.unread&&<span>有新回复</span>}</a>)}</div>{ready&&!visible.length&&<p>{query?'没有匹配的内容。':kind==='feedback'?'暂无问题记录，可以提交问题。':'暂无当前可查看的已发布内容。'}</p>}{cursor&&<button disabled={busy} onClick={()=>void load(true)}>加载更多</button>}</>}
 </>;
}
